name:                topoll
version:             0.1.0.0
github:              "Sorokin-Anton/topoll"
license:             BSD3
author:              "Anton Sorokin"
maintainer:          "ams200140@gmail.com"
copyright:           "2022 Anton Sorokin"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/topoll#readme>


ghc-options:
- -Wall
- -O2

dependencies:
- base >= 4.7 && < 5
- finite-typelits
- qlinear
- SmithNormalForm
- vector
- vector-algorithms
- containers
- bed-and-breakfast
- parallel
- random
- hmatrix
- named
- hvega
- ihaskell-hvega
- text
- optparse-generic

default-extensions:
- DataKinds
- ViewPatterns
- TypeOperators
- OverloadedLabels
- OverloadedStrings
- TypeApplications
- GADTs
- KindSignatures
- ImportQualifiedPost

library:
  source-dirs: src

executables:
  topoll-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topoll

tests:
  topoll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topoll
    - hspec
